default:
	@just --list

list:
	#!/usr/bin/env python3
	from pathlib import Path
	import re

	years = []
	for dir in Path(".").iterdir():
		if not re.search(r"^\d+$", dir.name):
			continue
		years.append(int(dir.name))
	years.sort()
	years.reverse()

	for year in years:
		days = []
		for file in (Path(".") / str(year)).iterdir():
			match = re.match(r"^(\d+)\.ts$", file.name)
			if not match:
				continue
			days.append(int(match.group(1)))
		days.sort()
		print(str(year) + ": " + ",".join(str(n) for n in days))

run year day:
	deno run --allow-read ./{{year}}/{{day}}.ts